/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: profile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "profile.pb-c.h"
void   drcctprof__profile__profile__init
                     (Drcctprof__Profile__Profile         *message)
{
  static const Drcctprof__Profile__Profile init_value = DRCCTPROF__PROFILE__PROFILE__INIT;
  *message = init_value;
}
size_t drcctprof__profile__profile__get_packed_size
                     (const Drcctprof__Profile__Profile *message)
{
  assert(message->base.descriptor == &drcctprof__profile__profile__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__profile__pack
                     (const Drcctprof__Profile__Profile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__profile__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__profile__pack_to_buffer
                     (const Drcctprof__Profile__Profile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__profile__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__Profile *
       drcctprof__profile__profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__Profile *)
     protobuf_c_message_unpack (&drcctprof__profile__profile__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__profile__free_unpacked
                     (Drcctprof__Profile__Profile *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__profile__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__sample__init
                     (Drcctprof__Profile__Sample         *message)
{
  static const Drcctprof__Profile__Sample init_value = DRCCTPROF__PROFILE__SAMPLE__INIT;
  *message = init_value;
}
size_t drcctprof__profile__sample__get_packed_size
                     (const Drcctprof__Profile__Sample *message)
{
  assert(message->base.descriptor == &drcctprof__profile__sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__sample__pack
                     (const Drcctprof__Profile__Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__sample__pack_to_buffer
                     (const Drcctprof__Profile__Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__Sample *
       drcctprof__profile__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__Sample *)
     protobuf_c_message_unpack (&drcctprof__profile__sample__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__sample__free_unpacked
                     (Drcctprof__Profile__Sample *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__metric_type__init
                     (Drcctprof__Profile__MetricType         *message)
{
  static const Drcctprof__Profile__MetricType init_value = DRCCTPROF__PROFILE__METRIC_TYPE__INIT;
  *message = init_value;
}
size_t drcctprof__profile__metric_type__get_packed_size
                     (const Drcctprof__Profile__MetricType *message)
{
  assert(message->base.descriptor == &drcctprof__profile__metric_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__metric_type__pack
                     (const Drcctprof__Profile__MetricType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__metric_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__metric_type__pack_to_buffer
                     (const Drcctprof__Profile__MetricType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__metric_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__MetricType *
       drcctprof__profile__metric_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__MetricType *)
     protobuf_c_message_unpack (&drcctprof__profile__metric_type__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__metric_type__free_unpacked
                     (Drcctprof__Profile__MetricType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__metric_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__metric__init
                     (Drcctprof__Profile__Metric         *message)
{
  static const Drcctprof__Profile__Metric init_value = DRCCTPROF__PROFILE__METRIC__INIT;
  *message = init_value;
}
size_t drcctprof__profile__metric__get_packed_size
                     (const Drcctprof__Profile__Metric *message)
{
  assert(message->base.descriptor == &drcctprof__profile__metric__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__metric__pack
                     (const Drcctprof__Profile__Metric *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__metric__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__metric__pack_to_buffer
                     (const Drcctprof__Profile__Metric *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__metric__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__Metric *
       drcctprof__profile__metric__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__Metric *)
     protobuf_c_message_unpack (&drcctprof__profile__metric__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__metric__free_unpacked
                     (Drcctprof__Profile__Metric *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__metric__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__context__init
                     (Drcctprof__Profile__Context         *message)
{
  static const Drcctprof__Profile__Context init_value = DRCCTPROF__PROFILE__CONTEXT__INIT;
  *message = init_value;
}
size_t drcctprof__profile__context__get_packed_size
                     (const Drcctprof__Profile__Context *message)
{
  assert(message->base.descriptor == &drcctprof__profile__context__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__context__pack
                     (const Drcctprof__Profile__Context *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__context__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__context__pack_to_buffer
                     (const Drcctprof__Profile__Context *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__context__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__Context *
       drcctprof__profile__context__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__Context *)
     protobuf_c_message_unpack (&drcctprof__profile__context__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__context__free_unpacked
                     (Drcctprof__Profile__Context *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__context__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__location__init
                     (Drcctprof__Profile__Location         *message)
{
  static const Drcctprof__Profile__Location init_value = DRCCTPROF__PROFILE__LOCATION__INIT;
  *message = init_value;
}
size_t drcctprof__profile__location__get_packed_size
                     (const Drcctprof__Profile__Location *message)
{
  assert(message->base.descriptor == &drcctprof__profile__location__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__location__pack
                     (const Drcctprof__Profile__Location *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__location__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__location__pack_to_buffer
                     (const Drcctprof__Profile__Location *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__location__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__Location *
       drcctprof__profile__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__Location *)
     protobuf_c_message_unpack (&drcctprof__profile__location__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__location__free_unpacked
                     (Drcctprof__Profile__Location *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__location__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__line__init
                     (Drcctprof__Profile__Line         *message)
{
  static const Drcctprof__Profile__Line init_value = DRCCTPROF__PROFILE__LINE__INIT;
  *message = init_value;
}
size_t drcctprof__profile__line__get_packed_size
                     (const Drcctprof__Profile__Line *message)
{
  assert(message->base.descriptor == &drcctprof__profile__line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__line__pack
                     (const Drcctprof__Profile__Line *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__line__pack_to_buffer
                     (const Drcctprof__Profile__Line *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__Line *
       drcctprof__profile__line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__Line *)
     protobuf_c_message_unpack (&drcctprof__profile__line__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__line__free_unpacked
                     (Drcctprof__Profile__Line *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__function__init
                     (Drcctprof__Profile__Function         *message)
{
  static const Drcctprof__Profile__Function init_value = DRCCTPROF__PROFILE__FUNCTION__INIT;
  *message = init_value;
}
size_t drcctprof__profile__function__get_packed_size
                     (const Drcctprof__Profile__Function *message)
{
  assert(message->base.descriptor == &drcctprof__profile__function__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__function__pack
                     (const Drcctprof__Profile__Function *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__function__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__function__pack_to_buffer
                     (const Drcctprof__Profile__Function *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__function__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__Function *
       drcctprof__profile__function__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__Function *)
     protobuf_c_message_unpack (&drcctprof__profile__function__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__function__free_unpacked
                     (Drcctprof__Profile__Function *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__function__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drcctprof__profile__source_file__init
                     (Drcctprof__Profile__SourceFile         *message)
{
  static const Drcctprof__Profile__SourceFile init_value = DRCCTPROF__PROFILE__SOURCE_FILE__INIT;
  *message = init_value;
}
size_t drcctprof__profile__source_file__get_packed_size
                     (const Drcctprof__Profile__SourceFile *message)
{
  assert(message->base.descriptor == &drcctprof__profile__source_file__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drcctprof__profile__source_file__pack
                     (const Drcctprof__Profile__SourceFile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drcctprof__profile__source_file__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drcctprof__profile__source_file__pack_to_buffer
                     (const Drcctprof__Profile__SourceFile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drcctprof__profile__source_file__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Drcctprof__Profile__SourceFile *
       drcctprof__profile__source_file__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Drcctprof__Profile__SourceFile *)
     protobuf_c_message_unpack (&drcctprof__profile__source_file__descriptor,
                                allocator, len, data);
}
void   drcctprof__profile__source_file__free_unpacked
                     (Drcctprof__Profile__SourceFile *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drcctprof__profile__source_file__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor drcctprof__profile__profile__field_descriptors[7] =
{
  {
    "metric_type",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Profile, n_metric_type),
    offsetof(Drcctprof__Profile__Profile, metric_type),
    &drcctprof__profile__metric_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Profile, n_sample),
    offsetof(Drcctprof__Profile__Profile, sample),
    &drcctprof__profile__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Profile, n_context),
    offsetof(Drcctprof__Profile__Profile, context),
    &drcctprof__profile__context__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Profile, n_location),
    offsetof(Drcctprof__Profile__Profile, location),
    &drcctprof__profile__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Profile, n_function),
    offsetof(Drcctprof__Profile__Profile, function),
    &drcctprof__profile__function__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_file",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Profile, n_source_file),
    offsetof(Drcctprof__Profile__Profile, source_file),
    &drcctprof__profile__source_file__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_table",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Drcctprof__Profile__Profile, n_string_table),
    offsetof(Drcctprof__Profile__Profile, string_table),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__profile__field_indices_by_name[] = {
  2,   /* field[2] = context */
  4,   /* field[4] = function */
  3,   /* field[3] = location */
  0,   /* field[0] = metric_type */
  1,   /* field[1] = sample */
  5,   /* field[5] = source_file */
  6,   /* field[6] = string_table */
};
static const ProtobufCIntRange drcctprof__profile__profile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor drcctprof__profile__profile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.Profile",
  "Profile",
  "Drcctprof__Profile__Profile",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__Profile),
  7,
  drcctprof__profile__profile__field_descriptors,
  drcctprof__profile__profile__field_indices_by_name,
  1,  drcctprof__profile__profile__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__profile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__sample__field_descriptors[2] =
{
  {
    "context_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Sample, context_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metric",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Sample, n_metric),
    offsetof(Drcctprof__Profile__Sample, metric),
    &drcctprof__profile__metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__sample__field_indices_by_name[] = {
  0,   /* field[0] = context_id */
  1,   /* field[1] = metric */
};
static const ProtobufCIntRange drcctprof__profile__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor drcctprof__profile__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.Sample",
  "Sample",
  "Drcctprof__Profile__Sample",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__Sample),
  2,
  drcctprof__profile__sample__field_descriptors,
  drcctprof__profile__sample__field_indices_by_name,
  1,  drcctprof__profile__sample__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__metric_type__field_descriptors[3] =
{
  {
    "value_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__MetricType, value_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__MetricType, unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "des",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__MetricType, des),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__metric_type__field_indices_by_name[] = {
  2,   /* field[2] = des */
  1,   /* field[1] = unit */
  0,   /* field[0] = value_type */
};
static const ProtobufCIntRange drcctprof__profile__metric_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drcctprof__profile__metric_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.MetricType",
  "MetricType",
  "Drcctprof__Profile__MetricType",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__MetricType),
  3,
  drcctprof__profile__metric_type__field_descriptors,
  drcctprof__profile__metric_type__field_indices_by_name,
  1,  drcctprof__profile__metric_type__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__metric_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__metric__field_descriptors[3] =
{
  {
    "int_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Metric, int_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uint_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Metric, uint_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Metric, str_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__metric__field_indices_by_name[] = {
  0,   /* field[0] = int_value */
  2,   /* field[2] = str_value */
  1,   /* field[1] = uint_value */
};
static const ProtobufCIntRange drcctprof__profile__metric__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drcctprof__profile__metric__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.Metric",
  "Metric",
  "Drcctprof__Profile__Metric",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__Metric),
  3,
  drcctprof__profile__metric__field_descriptors,
  drcctprof__profile__metric__field_indices_by_name,
  1,  drcctprof__profile__metric__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__metric__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__context__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Context, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Context, location_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Context, parent_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "children_id",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Drcctprof__Profile__Context, n_children_id),
    offsetof(Drcctprof__Profile__Context, children_id),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__context__field_indices_by_name[] = {
  3,   /* field[3] = children_id */
  0,   /* field[0] = id */
  1,   /* field[1] = location_id */
  2,   /* field[2] = parent_id */
};
static const ProtobufCIntRange drcctprof__profile__context__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor drcctprof__profile__context__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.Context",
  "Context",
  "Drcctprof__Profile__Context",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__Context),
  4,
  drcctprof__profile__context__field_descriptors,
  drcctprof__profile__context__field_indices_by_name,
  1,  drcctprof__profile__context__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__context__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__location__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Location, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Drcctprof__Profile__Location, n_line),
    offsetof(Drcctprof__Profile__Location, line),
    &drcctprof__profile__line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__location__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = line */
};
static const ProtobufCIntRange drcctprof__profile__location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor drcctprof__profile__location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.Location",
  "Location",
  "Drcctprof__Profile__Location",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__Location),
  2,
  drcctprof__profile__location__field_descriptors,
  drcctprof__profile__location__field_indices_by_name,
  1,  drcctprof__profile__location__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__line__field_descriptors[2] =
{
  {
    "function_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Line, function_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Line, line),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__line__field_indices_by_name[] = {
  0,   /* field[0] = function_id */
  1,   /* field[1] = line */
};
static const ProtobufCIntRange drcctprof__profile__line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor drcctprof__profile__line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.Line",
  "Line",
  "Drcctprof__Profile__Line",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__Line),
  2,
  drcctprof__profile__line__field_descriptors,
  drcctprof__profile__line__field_indices_by_name,
  1,  drcctprof__profile__line__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__function__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Function, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Function, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Function, system_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_file_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Function, source_file_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_line",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__Function, start_line),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__function__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  3,   /* field[3] = source_file_id */
  4,   /* field[4] = start_line */
  2,   /* field[2] = system_name */
};
static const ProtobufCIntRange drcctprof__profile__function__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor drcctprof__profile__function__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.Function",
  "Function",
  "Drcctprof__Profile__Function",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__Function),
  5,
  drcctprof__profile__function__field_descriptors,
  drcctprof__profile__function__field_indices_by_name,
  1,  drcctprof__profile__function__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__function__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drcctprof__profile__source_file__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__SourceFile, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__SourceFile, filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location_path",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__SourceFile, location_path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Drcctprof__Profile__SourceFile, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drcctprof__profile__source_file__field_indices_by_name[] = {
  1,   /* field[1] = filename */
  0,   /* field[0] = id */
  2,   /* field[2] = location_path */
  3,   /* field[3] = type */
};
static const ProtobufCIntRange drcctprof__profile__source_file__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor drcctprof__profile__source_file__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drcctprof.profile.SourceFile",
  "SourceFile",
  "Drcctprof__Profile__SourceFile",
  "drcctprof.profile",
  sizeof(Drcctprof__Profile__SourceFile),
  4,
  drcctprof__profile__source_file__field_descriptors,
  drcctprof__profile__source_file__field_indices_by_name,
  1,  drcctprof__profile__source_file__number_ranges,
  (ProtobufCMessageInit) drcctprof__profile__source_file__init,
  NULL,NULL,NULL    /* reserved[123] */
};
